final List<Map<String, String>> paperContent = [
  {
    'title': 'BAB I: PENDAHULUAN',
    'content':
        '1.1. Latar Belakang\n\nPerkembangan teknologi informasi dan komunikasi telah mengubah berbagai aspek kehidupan manusia, termasuk cara berbelanja. Belanja online kini menjadi alternatif utama bagi banyak orang, bahkan di daerah pedesaan. Desa Pemana, sebuah wilayah dengan karakteristik masyarakat yang unik, tidak luput dari fenomena ini. Salah satu model belanja online yang semakin populer di Desa Pemana adalah jasa titip (jastip) online. Fenomena ini menarik untuk dikaji karena menunjukkan adanya pergeseran perilaku konsumen dari yang sebelumnya tradisional menjadi lebih rasional dan modern.\n\nKonsumen rasional adalah mereka yang membuat keputusan pembelian berdasarkan pertimbangan logis, seperti harga, kualitas, dan efisiensi. Jastip online menawarkan berbagai keuntungan yang sejalan dengan prinsip-prinsip konsumen rasional, seperti akses terhadap produk yang tidak tersedia di pasar lokal, harga yang lebih kompetitif, dan kemudahan dalam bertransaksi. Penelitian ini bertujuan untuk menganalisis fenomena konsumen rasional di Desa Pemana dalam konteks meningkatnya popularitas jastip online sebagai pilihan utama dalam memenuhi kebutuhan mereka.',
  },
  {
    'title': 'BAB II: TINJAUAN PUSTAKA',
    'content':
        '2.1. Perilaku Konsumen\n\nPerilaku konsumen adalah studi tentang bagaimana individu, kelompok, dan organisasi memilih, membeli, menggunakan, dan membuang barang, jasa, ide, atau pengalaman untuk memuaskan kebutuhan dan keinginan mereka. Schiffman dan Kanuk (2008) mendefinisikan perilaku konsumen sebagai perilaku yang ditunjukkan konsumen dalam mencari, membeli, menggunakan, mengevaluasi, dan membuang produk dan jasa yang mereka harapkan akan memuaskan kebutuhan mereka.\n\n2.2. Konsumen Rasional\n\nTeori konsumen rasional menyatakan bahwa konsumen akan selalu berusaha memaksimalkan utilitas atau kepuasan mereka dengan anggaran yang terbatas. Keputusan pembelian didasarkan pada analisis biaya-manfaat yang cermat. Menurut Mowen dan Minor (2002), konsumen rasional memiliki karakteristik sebagai berikut: (1) memiliki informasi yang lengkap tentang produk, (2) mampu memproses informasi secara logis, dan (3) selalu memilih alternatif terbaik untuk memaksimalkan kepuasan.\n\n2.3. Jasa Titip (Jastip) Online\n\nJastip online adalah sebuah model bisnis di mana seseorang (penyedia jastip) menawarkan jasa untuk membelikan produk dari lokasi tertentu (biasanya kota besar atau luar negeri) untuk orang lain (konsumen) dengan imbalan sejumlah biaya jasa. Model ini berkembang pesat seiring dengan meningkatnya penggunaan media sosial dan e-commerce. Jastip online memungkinkan konsumen di daerah terpencil seperti Desa Pemana untuk mendapatkan akses ke produk-produk yang sebelumnya sulit dijangkau.',
  },
  {
    'title': 'BAB III: METODOLOGI PENELITIAN',
    'content':
        '3.1. Pendekatan Penelitian\n\nPenelitian ini menggunakan pendekatan kualitatif dengan metode studi kasus. Pendekatan ini dipilih karena memungkinkan peneliti untuk memahami secara mendalam fenomena konsumen rasional dan penggunaan jastip online dalam konteks spesifik Desa Pemana.\n\n3.2. Lokasi dan Waktu Penelitian\n\nPenelitian ini dilakukan di Desa Pemana, Kabupaten Sikka, Nusa Tenggara Timur. Waktu penelitian dilaksanakan selama tiga bulan, dari bulan Juni hingga Agustus 2023.\n\n3.3. Subjek Penelitian\n\nSubjek penelitian adalah warga Desa Pemana yang aktif menggunakan layanan jastip online. Pemilihan subjek dilakukan dengan teknik purposive sampling, yaitu memilih informan yang dianggap paling mengetahui dan dapat memberikan informasi yang relevan dengan topik penelitian.\n\n3.4. Teknik Pengumpulan Data\n\nData dikumpulkan melalui tiga cara: (1) Wawancara mendalam dengan para pengguna jastip online, (2) Observasi partisipatif terhadap aktivitas transaksi jastip, dan (3) Studi dokumentasi dari riwayat transaksi dan percakapan di grup media sosial yang digunakan untuk jastip.\n\n3.5. Analisis Data\n\nData yang terkumpul dianalisis menggunakan model analisis interaktif dari Miles dan Huberman, yang meliputi tiga tahap: reduksi data, penyajian data, dan penarikan kesimpulan.',
  },
  {
    'title': 'BAB IV: HASIL DAN PEMBAHASAN',
    'content':
        '4.1. Profil Konsumen Jastip Online di Desa Pemana\n\nKonsumen jastip online di Desa Pemana didominasi oleh kalangan muda, terutama perempuan, dengan rentang usia 18-35 tahun. Mereka umumnya adalah pelajar, mahasiswa, dan ibu rumah tangga yang aktif menggunakan media sosial seperti Facebook dan WhatsApp. Tingkat pendidikan mereka bervariasi, namun sebagian besar telah menyelesaikan pendidikan menengah atas.\n\n4.2. Faktor-Faktor yang Mendorong Pilihan Jastip Online\n\nBerdasarkan hasil wawancara, terdapat beberapa faktor utama yang mendorong warga Desa Pemana memilih jastip online:\n\na. Ketersediaan Produk: Banyak produk, terutama produk fashion, kosmetik, dan elektronik terbaru, tidak tersedia di toko-toko lokal. Jastip online menjadi satu-satunya cara untuk mendapatkan produk-produk tersebut.\n\nb. Harga yang Lebih Murah: Meskipun ada biaya jasa, harga total produk yang dibeli melalui jastip seringkali lebih murah dibandingkan jika harus membelinya sendiri ke kota besar, karena dapat menghemat biaya transportasi dan akomodasi.\n\nc. Efisiensi Waktu dan Tenaga: Konsumen tidak perlu membuang waktu dan tenaga untuk bepergian jauh. Mereka cukup memesan melalui smartphone dan menunggu barang diantar.\n\nd. Kepercayaan dan Hubungan Sosial: Penyedia jastip umumnya adalah orang yang dikenal atau masih memiliki hubungan kekerabatan, sehingga tingkat kepercayaan lebih tinggi dibandingkan berbelanja di platform e-commerce yang penjualnya tidak dikenal.\n\n4.3. Analisis Perilaku Konsumen Rasional\n\nFenomena ini menunjukkan ciri-ciri kuat dari perilaku konsumen rasional. Keputusan pembelian tidak lagi didasarkan pada kebiasaan atau emosi semata, tetapi melalui pertimbangan yang matang. Konsumen secara aktif mencari informasi produk, membandingkan harga, dan menghitung total biaya yang harus dikeluarkan. Mereka telah mampu melakukan analisis biaya-manfaat sederhana, di mana manfaat yang diperoleh (produk yang diinginkan, harga lebih murah, efisiensi) dinilai lebih besar daripada biayanya (biaya jasa titip).',
  },
  {
    'title': 'BAB V: KESIMPULAN DAN SARAN',
    'content':
        '5.1. Kesimpulan\n\nBerdasarkan hasil penelitian, dapat disimpulkan bahwa fenomena jastip online di Desa Pemana merupakan manifestasi dari perilaku konsumen rasional. Konsumen di Desa Pemana tidak lagi pasif, melainkan aktif mencari cara untuk memaksimalkan kepuasan mereka dengan sumber daya yang terbatas. Faktor-faktor seperti ketersediaan produk, harga yang lebih kompetitif, efisiensi, dan kepercayaan menjadi pendorong utama dalam memilih jastip online. Fenomena ini menandakan adanya transformasi perilaku konsumen di daerah pedesaan yang semakin cerdas dan adaptif terhadap perkembangan teknologi.\n\n5.2. Saran\n\na. Bagi Pelaku Usaha Lokal: Pelaku usaha di Desa Pemana perlu beradaptasi dengan perubahan ini, misalnya dengan menyediakan produk-produk yang lebih variatif atau bahkan membuka layanan jastip sendiri untuk menjangkau pasar yang lebih luas.\n\nb. Bagi Pemerintah Desa: Pemerintah desa dapat memberikan dukungan berupa pelatihan literasi digital dan kewirausahaan bagi para penyedia jastip untuk meningkatkan kualitas layanan dan profesionalisme mereka.\n\nc. Bagi Peneliti Selanjutnya: Penelitian lebih lanjut dapat dilakukan untuk mengkaji dampak ekonomi dan sosial dari fenomena jastip online terhadap masyarakat Desa Pemana secara lebih komprehensif.',
  },
];
